[build]
  publish = "."
  functions = "netlify/functions"

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "https://fluxyos.netlify.app/fluxyos"
  to = "https://fluxyos.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://fluxyos.netlify.app/*"
  to = "https://fluxyos.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.fluxyos.com/*"
  to = "https://fluxyos.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ecommerce-brands"
  to = "/use-cases/ecommerce-brands"
  status = 301
  force = true

[[redirects]]
  from = "/marketing-agencies"
  to = "/use-cases/marketing-agencies"
  status = 301
  force = true

[[redirects]]
  from = "/dropshippers-digital-ads"
  to = "/use-cases/dropshippers-digital-ads"
  status = 301
  force = true

[[redirects]]
  from = "/manufacturing"
  to = "/use-cases/manufacturing"
  status = 301
  force = true

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/fluxyos.html"
  status = 200
  force = true
