[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/fluxyos.html"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

[build]
  publish = "."
  functions = "netlify/functions"
