const{test,expect}=require('./public-test');
for(const locale of['en','id'])for(const width of[1440,1024,768,390,320])test(`${locale} cfo-finance-teams ${width}`,async({page,request})=>{
 const prefix=locale==='id'?'/id':'',errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith('http://127.0.0.1:8765')&&r.status()>=400)missing.push(r.url())});
 await page.setViewportSize({width,height:900});await page.goto(prefix+'/use-cases/cfo-finance-teams',{waitUntil:'domcontentloaded'});await expect(page.locator('main')).toHaveAttribute('data-cfo-ready','true');await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('html')).toHaveAttribute('lang',locale);
 await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href','https://fluxyos.com'+prefix+'/use-cases/cfo-finance-teams');for(const lang of['en','id','x-default'])await expect(page.locator(`link[hreflang="${lang}"]`)).toHaveAttribute('href','https://fluxyos.com'+(lang==='id'?'/id':'')+'/use-cases/cfo-finance-teams');
 expect((await page.title()).length).toBeLessThanOrEqual(60);expect((await page.locator('meta[name=description]').getAttribute('content')).length).toBeLessThanOrEqual(160);
 const schemas=(await page.locator('script[type="application/ld+json"]').allTextContents()).map(JSON.parse);expect(schemas.map(s=>s['@type'])).toEqual(expect.arrayContaining(['Organization','SoftwareApplication','FAQPage','BreadcrumbList']));for(const q of schemas.find(s=>s['@type']==='FAQPage').mainEntity){expect(await page.locator('#faq').textContent()).toContain(q.name);expect(await page.locator('#faq').textContent()).toContain(q.acceptedAnswer.text)}
 const panelHeights=[];for(let i=0;i<3;i++){await page.locator(`#cf-tab-${i}`).click();await expect(page.locator(`#cf-panel-${i}`)).toBeVisible();await expect(page.locator('[role=tabpanel]:visible')).toHaveCount(1);panelHeights.push(await page.locator(`#cf-panel-${i}`).evaluate(e=>e.getBoundingClientRect().height))}expect(Math.max(...panelHeights)-Math.min(...panelHeights),'record switch changes panel height').toBeLessThanOrEqual(1);await page.locator('#cf-tab-2').focus();await page.keyboard.press('Home');await expect(page.locator('#cf-tab-0')).toBeFocused();await page.keyboard.press('ArrowRight');await expect(page.locator('#cf-tab-1')).toBeFocused();await expect(page.locator('#cf-panel-1')).toBeVisible();await page.keyboard.press('End');await expect(page.locator('#cf-tab-2')).toBeFocused();await page.keyboard.press('ArrowRight');await expect(page.locator('#cf-tab-0')).toBeFocused();
 const y=await page.evaluate(()=>scrollY);await page.locator('#cf-tab-1').click();expect(Math.abs(await page.evaluate(()=>scrollY)-y)).toBeLessThan(3);
 const compare=page.locator('[data-cf-compare]');await compare.click();await expect(compare).toHaveAttribute('aria-expanded','true');await expect(page.locator('#cf-match-details')).toBeVisible();await compare.click();await expect(page.locator('#cf-match-details')).toBeHidden();
 const faq=page.locator('#faq details').first();await faq.locator('summary').focus();await page.keyboard.press('Enter');await expect(faq).toHaveAttribute('open','');await expect(faq.locator('p')).toBeVisible();await page.keyboard.press('Enter');await expect(faq).not.toHaveAttribute('open','');
 for(const section of await page.locator('main section').all()){await section.scrollIntoViewIfNeeded();await page.waitForTimeout(60)}await page.locator('footer').waitFor();for(const img of await page.locator('main img:visible').all()){await img.scrollIntoViewIfNeeded();await expect(img).toHaveJSProperty('complete',true);expect(await img.evaluate(e=>e.naturalWidth)).toBeGreaterThan(0);await expect(img).toHaveAttribute('alt',/.*/)}
 const urls=new Set(await page.locator('main a').evaluateAll(es=>es.map(e=>e.getAttribute('href')).filter(h=>h?.startsWith('/'))));for(const href of urls)expect((await request.get(href)).status(),href).toBe(200);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);expect(missing).toEqual([]);
 if(width===1440||width===390){await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(900);await page.screenshot({path:`.qa/cfo/${locale}-${width}-hero.png`});await page.locator('#walkthrough').scrollIntoViewIfNeeded();await page.waitForTimeout(650);await page.screenshot({path:`.qa/cfo/${locale}-${width}-walkthrough.png`});await page.screenshot({path:`.qa/cfo/${locale}-${width}-full.png`,fullPage:true})}
});
test('reduced motion and no-JS content remain usable',async({page,browser})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/use-cases/cfo-finance-teams',{waitUntil:'domcontentloaded'});await expect(page.locator('main')).toHaveAttribute('data-cfo-ready','true');expect(await page.locator('.cf-hero').evaluate(e=>getComputedStyle(e,'::before').animationName)).toBe('none');await page.locator('#cf-tab-2').click();expect(await page.locator('#cf-panel-2').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');const ctx=await browser.newContext({javaScriptEnabled:false}),p=await ctx.newPage();await p.goto('http://127.0.0.1:8765/use-cases/cfo-finance-teams',{waitUntil:'domcontentloaded'});await expect(p.locator('h1')).toBeVisible();await expect(p.locator('.cf-stages')).toBeHidden();await expect(p.locator('.cf-tour-panel:visible')).toHaveCount(3);await p.locator('details').first().locator('summary').click();await expect(p.locator('details').first()).toHaveAttribute('open','');await ctx.close()});
test('explicit record animation finishes, can pause, and never changes focus',async({page})=>{
 await page.clock.install();await page.goto('/use-cases/cfo-finance-teams',{waitUntil:'domcontentloaded'});await expect(page.locator('main')).toHaveAttribute('data-cfo-ready','true');const tour=page.locator('[data-cf-tour]'),play=page.locator('[data-cf-replay]');await tour.scrollIntoViewIfNeeded();await play.focus();await page.keyboard.press('Enter');await expect(play).toHaveAttribute('aria-pressed','true');await page.clock.runFor(1450);await expect(tour).toHaveAttribute('data-active-step','1');await expect(play).toBeFocused();await page.keyboard.press('Enter');await expect(tour).toHaveAttribute('data-playing','false');await page.clock.runFor(4000);await expect(tour).toHaveAttribute('data-active-step','1');await page.keyboard.press('Enter');await page.clock.runFor(4300);await expect(tour).toHaveAttribute('data-active-step','2');await expect(play).toHaveAttribute('aria-pressed','false');await expect(play).toBeFocused();await page.emulateMedia({reducedMotion:'reduce'});await expect(play).toBeDisabled();await page.locator('#cf-tab-0').click();await expect(tour).toHaveAttribute('data-active-step','0');
});
test('shared navigation and finance asset quality',async({page,request})=>{
 await page.goto('/use-cases/cfo-finance-teams',{waitUntil:'domcontentloaded'});await expect(page.locator('nav[data-animate=nav]')).toHaveAttribute('data-public-nav-ready','true');await page.locator('[aria-controls="agency-nav-panel-0"]').focus();await page.keyboard.press('ArrowDown');await expect(page.locator('#agency-nav-panel-0')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#agency-nav-panel-0')).toBeHidden();const fs=require('fs');for(const asset of['reconciliation','period-close','report-package','finance-review']){expect(fs.statSync(`assets/images/cfo-finance/${asset}.webp`).size).toBeLessThan(32000);expect((await request.get(`/assets/images/cfo-finance/${asset}.webp`)).status()).toBe(200)}await page.setViewportSize({width:390,height:900});await page.locator('.mobile-menu-toggle').click();await expect(page.locator('#mobile-menu')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#mobile-menu')).toBeHidden();
});
