const{test,expect}=require('@playwright/test'),manifest=require('../assets/images/navbar-3d/manifest.json');
for(const locale of['en','id'])for(const width of[1440,1024,768,390,320])test(`${locale} public navbar ${width}`,async({page,request})=>{
 const prefix=locale==='id'?'/id':'',errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:1000});await page.goto(prefix+'/fluxyos',{waitUntil:'domcontentloaded'});const nav=page.locator('nav[data-animate=nav]');await expect(nav).toHaveAttribute('data-public-nav-ready','true');
 if(width>=1024){for(const i of[0,1,2]){const trigger=nav.locator(`[aria-controls="agency-nav-panel-${i}"]`);await trigger.focus();await page.keyboard.press('ArrowDown');const panel=page.locator(`#agency-nav-panel-${i}`);await expect(panel).toBeVisible();await expect(panel.locator('a').first()).toBeFocused();for(const image of await panel.locator('[data-nav-icon]').all()){await image.scrollIntoViewIfNeeded();await expect(image).toHaveJSProperty('complete',true);expect(await image.evaluate(e=>e.naturalWidth)).toBeGreaterThanOrEqual(144);await expect(image).not.toHaveAttribute('data-icon-fallback','true');}await page.keyboard.press('Escape');await expect(panel).not.toBeVisible();await expect(trigger).toBeFocused();await expect(trigger).toHaveAttribute('aria-expanded','false');}
 const items=nav.locator('a[data-nav-entry]').filter({has:page.locator('img')});expect(await items.count()).toBe(36);
 }else{await nav.locator('.mobile-menu-toggle').click();await expect(page.locator('#mobile-menu')).toBeVisible();const items=page.locator('#mobile-menu [data-nav-entry]');await expect(items).toHaveCount(18);for(const item of await items.all()){await item.scrollIntoViewIfNeeded();const img=item.locator('[data-nav-icon]');await expect(img).toHaveJSProperty('complete',true);expect(await img.evaluate(e=>e.naturalWidth)).toBeGreaterThanOrEqual(144);await expect(img).not.toHaveAttribute('data-icon-fallback','true');expect(await item.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);}await items.last().focus();await page.keyboard.press('Escape');await expect(page.locator('#mobile-menu')).not.toBeVisible();await expect(nav.locator('.mobile-menu-toggle')).toBeFocused();}
 // Batch static DOM checks rather than making hundreds of browser round trips.
 const inventory=await nav.locator('[data-nav-entry]').evaluateAll(entries=>entries.map(entry=>{const image=entry.querySelector('img'),box=getComputedStyle(entry.querySelector('.public-nav-icon'));return{id:entry.dataset.navEntry,href:entry.getAttribute('href'),src:image.getAttribute('src'),alt:image.getAttribute('alt'),size:[parseFloat(box.width),parseFloat(box.height)]};}));
 for(const[id,m]of Object.entries(manifest)){const entries=inventory.filter(entry=>entry.id===id);expect(entries).toHaveLength(2);for(const entry of entries){expect(entry.href).toBe(prefix+m.route);expect(entry.src).toBe('/assets/images/navbar-3d/'+m.asset);expect(entry.alt).toBe('');expect(entry.size).toEqual([48,48]);}}
 await Promise.all(Object.values(manifest).map(async m=>expect((await request.get(prefix+m.route)).status()).toBe(200)));
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
 if(width===1440){for(const i of[0,1]){const trigger=nav.locator(`[aria-controls="agency-nav-panel-${i}"]`);await trigger.focus();await page.keyboard.press('ArrowDown');await expect(page.locator(`#agency-nav-panel-${i}`)).toBeVisible();await page.waitForTimeout(300);await page.screenshot({path:`.qa/public-navbar/${locale}-${width}-${i}.png`});await page.keyboard.press('Escape');}}
 if(width===390){await nav.locator('.mobile-menu-toggle').click();await page.locator('#mobile-menu').evaluate(e=>e.scrollTop=0);await page.waitForTimeout(350);await page.screenshot({path:`.qa/public-navbar/${locale}-${width}-mobile.png`});}
});
test('fallback, hover, reduced motion and high-density assets',async({page})=>{
 await page.route('**/navbar-3d/pos-terminal.webp',r=>r.abort());await page.goto('/fluxyos',{waitUntil:'domcontentloaded'});await page.locator('[aria-controls="agency-nav-panel-0"]').hover();const entry=page.locator('#agency-nav-panel-0 [data-nav-entry="point-of-sale"]');await expect(entry.locator('img')).toHaveAttribute('data-icon-fallback','true');await expect(entry.locator('img')).toHaveAttribute('src','/assets/images/navbar-3d/fallback.svg');await entry.hover();await page.waitForTimeout(300);expect(await entry.locator('img').evaluate(e=>getComputedStyle(e).transform)).not.toBe('none');await page.emulateMedia({reducedMotion:'reduce'});expect(await entry.locator('img').evaluate(e=>getComputedStyle(e).transform)).toBe('none');
});

test('language routes and touch navigation remain usable',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:900},hasTouch:true,deviceScaleFactor:3});const page=await context.newPage();await page.goto('http://127.0.0.1:8765/id/fluxyos',{waitUntil:'domcontentloaded'});await page.locator('.mobile-menu-toggle').tap();await page.locator('#mobile-menu [data-nav-entry="cfo-finance"]').tap();await expect(page).toHaveURL(/\/id\/use-cases\/cfo-finance-teams$/);await context.close();
});
test('asset budget and every synchronized page use the manifest',async()=>{
 const fs=require('fs'),path=require('path'),navTools=require('../scripts/sync-marketing-nav');let total=0;
 for(const m of Object.values(manifest)){const size=fs.statSync(path.join('assets/images/navbar-3d',m.asset)).size;expect(size).toBeLessThanOrEqual(12*1024);total+=size;}expect(total).toBeLessThanOrEqual(216*1024);
 for(const f of navTools.pages()){const nav=fs.readFileSync(f,'utf8').match(navTools.NAV)[0];for(const id of Object.keys(manifest))expect(nav.match(new RegExp(`data-nav-entry="${id}"`,'g'))?.length,f+': '+id).toBe(2);expect(nav).not.toContain('dropshippers-digital-ads');}
});
