const {test,expect}=require('./public-test');
const fs=require('fs');
for(const locale of ['en','id'])for(const width of [1440,768,390,320])test(`${locale} restaurant flow at ${width}`,async({page,request})=>{
 await page.setViewportSize({width,height:900});const errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(['POST','PUT','PATCH','DELETE'].includes(r.method())&&!r.url().includes('google'))writes.push(r.url())});
 const prefix=locale==='id'?'/id':'',url=`${prefix}/use-cases/restaurants-cafes`;await page.goto(url,{waitUntil:'domcontentloaded'});await expect(page.locator('[data-map-step][aria-selected="true"]')).toHaveCount(1);await expect(page.locator('.rc-map-panel:visible')).toHaveCount(1);
 const tabs=page.locator('[data-map-step]');const initialHeight=await page.locator('.rc-map').evaluate(e=>e.getBoundingClientRect().height);for(let i=0;i<5;i++){await tabs.nth(i).click();await expect(page.locator(`#rc-panel-${i}`)).toBeVisible();expect(await page.locator(`#rc-panel-${i} .rc-window-body`).evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);await expect(page.locator('.rc-map-panel:visible')).toHaveCount(1);await expect(tabs.nth(i)).toHaveAttribute('aria-selected','true');expect(Math.abs(await page.locator('.rc-map').evaluate(e=>e.getBoundingClientRect().height)-initialHeight)).toBeLessThan(2);}
 await tabs.nth(4).focus();await page.keyboard.press('Home');await expect(tabs.nth(0)).toBeFocused();await page.keyboard.press('ArrowRight');await expect(tabs.nth(1)).toBeFocused();await page.keyboard.press('End');await expect(tabs.nth(4)).toBeFocused();
 await page.locator('[data-scenario-next]').click();await expect(page.locator('#rc-scenario-1')).toBeVisible();await expect(page.locator('[data-scenario-next]')).toBeDisabled();await page.locator('[data-scenario-prev]').click();await expect(page.locator('#rc-scenario-0')).toBeVisible();
 const faq=page.locator('#ingredients details').nth(1);await faq.locator('summary').focus();await page.keyboard.press('Enter');await expect(faq).toHaveAttribute('open','');
 await page.locator('.rc-section-nav a[href="#accounting"]').click();await expect(page).toHaveURL(/#accounting$/);await expect(page.locator('#accounting h2')).toBeInViewport();
 for(let y=0;y<await page.evaluate(()=>document.documentElement.scrollHeight);y+=650){await page.evaluate(y=>scrollTo(0,y),y);await page.waitForTimeout(30)}await page.waitForTimeout(700);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);expect(writes).toEqual([]);
 await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('html')).toHaveAttribute('lang',locale);await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href','https://fluxyos.com'+url);expect((await page.title()).length).toBeLessThanOrEqual(60);expect((await page.locator('meta[name=description]').getAttribute('content')).length).toBeLessThanOrEqual(160);
 const schemas=await page.locator('script[type="application/ld+json"]').evaluateAll(es=>es.map(e=>JSON.parse(e.textContent)));expect(schemas.map(s=>s['@type'])).toEqual(expect.arrayContaining(['Organization','SoftwareApplication','FAQPage','BreadcrumbList']));
 const links=await page.locator('main a').evaluateAll(as=>[...new Set(as.map(a=>a.getAttribute('href')))].filter(h=>h.startsWith('/')));for(const link of links)expect((await request.get(link)).status(),link).toBe(200);
 const nav=page.locator('nav[data-animate=nav]');await expect(nav.locator(`a[href="${prefix}/use-cases/restaurants-cafes"]`)).toHaveCount(locale==='id'?3:2);await expect(nav.locator('a[href*="dropshippers"]')).toHaveCount(0);
 if(width===390){await page.screenshot({path:`.qa/restaurants-cafes/verified-${locale}-${width}.png`,fullPage:true});}
 if(width===1440){await page.screenshot({path:`.qa/restaurants-cafes/verified-${locale}-${width}.png`,fullPage:true});}
});
test('reduced motion and live preference changes',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/use-cases/restaurants-cafes',{waitUntil:'domcontentloaded'});await page.locator('[data-map-step="4"]').click();expect(await page.locator('#rc-panel-4 .rc-window').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');await expect(page.locator('#accounting h2')).toBeVisible();await page.emulateMedia({reducedMotion:'no-preference'});await page.emulateMedia({reducedMotion:'reduce'});await expect(page.locator('.ag-page')).not.toHaveClass(/ag-motion-ready/);});
test('no-JS retains all workflow and planning explanations',async({browser})=>{const context=await browser.newContext({javaScriptEnabled:false});const page=await context.newPage();await page.goto('http://127.0.0.1:8765/use-cases/restaurants-cafes',{waitUntil:'domcontentloaded'});await expect(page.locator('.rc-map-panel:visible')).toHaveCount(5);await expect(page.locator('.rc-scenario:visible')).toHaveCount(2);await context.close();});
test('retired routes redirect to migrated content',async({page})=>{for(const locale of ['','/id']){await page.goto(`${locale}/use-cases/dropshippers-digital-ads`,{waitUntil:'domcontentloaded'});await expect(page).toHaveURL(new RegExp(`${locale}/use-cases/ecommerce-brands$`));await expect(page.locator('main')).toContainText(locale?'ongkos kurir':'courier charges');}const config=fs.readFileSync('deploy/_redirects.marketing','utf8');expect(config).toMatch(/\/use-cases\/dropshippers-digital-ads\s+\/use-cases\/ecommerce-brands\s+301!/);expect(config).toMatch(/\/id\/use-cases\/dropshippers-digital-ads\s+\/id\/use-cases\/ecommerce-brands\s+301!/);});

test('shared navigation and language route work',async({page})=>{
 await page.setViewportSize({width:1440,height:900});await page.goto('/use-cases/restaurants-cafes',{waitUntil:'domcontentloaded'});const language=page.locator('nav a').filter({hasText:'Bahasa (ID)'});const group=language.locator('xpath=ancestor::div[contains(concat(" ", normalize-space(@class), " "), " group ")][1]');await group.locator(':scope > button').click();await language.click();await expect(page).toHaveURL(/\/id\/use-cases\/restaurants-cafes$/);await expect(page.locator('h1')).toContainText('Pahami bisnis');
 await page.setViewportSize({width:390,height:900});const toggle=page.locator('.mobile-menu-toggle');await toggle.click();await expect(toggle).toHaveAttribute('aria-expanded','true');await expect(page.locator('#mobile-menu a[href="/id/use-cases/restaurants-cafes"]')).toBeVisible();await page.locator('#mobile-menu a').first().focus();await page.keyboard.press('Escape');await expect(toggle).toHaveAttribute('aria-expanded','false');await expect(toggle).toBeFocused();
});

test('automatic tour progresses without scrolling and stops for reading',async({page})=>{
 await page.clock.install();await page.setViewportSize({width:390,height:900});await page.goto('/use-cases/restaurants-cafes',{waitUntil:'domcontentloaded'});const map=page.locator('[data-finance-map]');await map.scrollIntoViewIfNeeded();await page.mouse.move(0,0);await expect(map).toHaveClass(/is-playing/);const before=await page.evaluate(()=>scrollY);await page.clock.runFor(8600);await expect(page.locator('[data-map-step="1"]')).toHaveAttribute('aria-selected','true');expect(await page.evaluate(()=>scrollY)).toBe(before);
 await page.locator('[data-map-step="3"]').click();await expect(map).not.toHaveClass(/is-playing/);await page.clock.runFor(17000);await expect(page.locator('[data-map-step="3"]')).toHaveAttribute('aria-selected','true');await expect(page.locator('[data-map-playback]')).toHaveText('Play tour');await page.locator('[data-map-playback]').focus();await page.keyboard.press('Enter');await page.mouse.move(0,0);await expect(map).toHaveClass(/is-playing/);await page.clock.runFor(8600);await expect(page.locator('[data-map-step="4"]')).toHaveAttribute('aria-selected','true');await page.locator('[data-map-step="3"]').click();
 await page.emulateMedia({reducedMotion:'reduce'});await expect(map).not.toHaveClass(/is-playing/);await page.clock.runFor(17000);await expect(page.locator('[data-map-step="3"]')).toHaveAttribute('aria-selected','true');await expect(page.locator('main')).not.toContainText('Illustrative walkthrough');
});

test('pointer Play control resumes after selecting a stage',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.goto('/use-cases/restaurants-cafes',{waitUntil:'domcontentloaded'});await page.locator('[data-map-step="3"]').click();const control=page.locator('[data-map-playback]');await expect(control).toHaveText('Play tour');await control.click();await page.mouse.move(0,0);await expect(control).toHaveText('Pause tour');await expect(page.locator('[data-finance-map]')).toHaveClass(/is-playing/);
});
