const{test,expect}=require('./public-test'),fs=require('fs');
for(const locale of['en','id'])for(const width of[1440,1024,768,390,320])test(`${locale} retail page ${width}`,async({page,request})=>{
 const prefix=locale==='id'?'/id':'',errors=[],missing=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith('http://127.0.0.1:8765')&&r.status()>=400)missing.push(r.url())});
 await page.setViewportSize({width,height:1000});await page.goto(prefix+'/use-cases/retail-franchises',{waitUntil:'domcontentloaded'});await expect(page.locator('[data-retail-tour]')).toHaveAttribute('data-enhanced','true');
 await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('html')).toHaveAttribute('lang',locale);
 await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href','https://fluxyos.com'+prefix+'/use-cases/retail-franchises');
 for(const lang of['en','id','x-default'])await expect(page.locator(`link[hreflang="${lang}"]`)).toHaveAttribute('href','https://fluxyos.com'+(lang==='id'?'/id':'')+'/use-cases/retail-franchises');
 const scripts=await page.locator('script[type="application/ld+json"]').allTextContents(),schemas=scripts.map(s=>JSON.parse(s));expect(schemas.map(s=>s['@type'])).toEqual(expect.arrayContaining(['Organization','SoftwareApplication','FAQPage','BreadcrumbList']));
 const faqSchema=schemas.find(s=>s['@type']==='FAQPage');for(const entry of faqSchema.mainEntity){await expect(page.locator('#faq summary').filter({hasText:entry.name})).toBeVisible();expect(await page.locator('#faq').textContent()).toContain(entry.acceptedAnswer.text);}
 const tour=page.locator('[data-retail-tour]');for(const n of[0,1,2]){await tour.locator(`[data-rf-step="${n}"]`).click();await expect(tour.locator(`#rf-panel-${n}`)).toBeVisible();const overlap=await tour.evaluate(e=>{const panel=e.querySelector('.rf-tour-panel:not([hidden])').getBoundingClientRect(),note=e.querySelector('.rf-source-note').getBoundingClientRect();return panel.bottom>note.top});expect(overlap,'tour content overlaps its source note').toBe(false);}
 const next=page.locator('[data-rf-next]'),carousel=page.locator('.rf-walk-carousel');await next.scrollIntoViewIfNeeded();await next.click();await expect.poll(()=>carousel.evaluate(e=>e.scrollLeft)).toBeGreaterThan(50);await carousel.focus();await page.keyboard.press('End');await expect(page.locator('[data-rf-status]')).toContainText('/ 4');await expect(next).toBeDisabled();expect(await carousel.evaluate(e=>e.scrollWidth-e.clientWidth-e.scrollLeft)).toBeLessThanOrEqual(3);await page.keyboard.press('Home');await expect(page.locator('[data-rf-status]')).toContainText('1–');
 const faq=page.locator('#faq details').first();await faq.locator('summary').click();await expect(faq).toHaveAttribute('open','');await expect(faq.locator('p')).toBeVisible();
 for(const section of await page.locator('main section').all()){await section.scrollIntoViewIfNeeded();await page.waitForTimeout(60);}await page.locator('footer').waitFor();
 for(const img of await page.locator('main img:visible').all()){await img.scrollIntoViewIfNeeded();await expect(img).toHaveJSProperty('complete',true);expect(await img.evaluate(e=>e.naturalWidth)).toBeGreaterThan(0);await expect(img).toHaveAttribute('alt',/.*/);}
 const urls=new Set(await page.locator('main a').evaluateAll(es=>es.map(e=>e.getAttribute('href')).filter(h=>h?.startsWith('/'))));for(const href of urls)expect((await request.get(href)).status(),href).toBe(200);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);expect(missing).toEqual([]);
 await expect(page.locator('body')).not.toContainText(/Illustrative walkthrough|sample figures|dummy data|Moka POS|WhatsApp, email/i);
 if(width===1440||width===390){await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(800);await page.screenshot({path:`.qa/retail/${locale}-${width}-final-hero.png`});await page.locator('#outlets').scrollIntoViewIfNeeded();await page.waitForTimeout(650);await page.screenshot({path:`.qa/retail/${locale}-${width}-outlets.png`});await page.locator('#how-it-works').scrollIntoViewIfNeeded();await page.waitForTimeout(650);await page.screenshot({path:`.qa/retail/${locale}-${width}-walkthrough.png`});}
});
test('automatic tour respects reading, manual choices, viewport and reduced motion',async({page})=>{
 await page.clock.install();await page.setViewportSize({width:1440,height:1000});await page.goto('/use-cases/retail-franchises',{waitUntil:'domcontentloaded'});const tour=page.locator('[data-retail-tour]');await expect(tour).toHaveClass(/is-playing/);const y=await page.evaluate(()=>scrollY);await page.clock.runFor(8600);await expect(tour).toHaveAttribute('data-active-step','1');expect(await page.evaluate(()=>scrollY)).toBe(y);expect(await page.evaluate(()=>document.activeElement.tagName)).toBe('BODY');
 await tour.hover();await page.clock.runFor(8600);await expect(tour).toHaveAttribute('data-active-step','1');await page.mouse.move(1,990);await page.clock.runFor(8600);await expect(tour).toHaveAttribute('data-active-step','2');
 await tour.locator('[data-rf-step="0"]').click();await page.clock.runFor(8600);await expect(tour).toHaveAttribute('data-active-step','0');await page.keyboard.press('ArrowRight');await expect(tour.locator('[data-rf-step="1"]')).toBeFocused();await expect(tour).toHaveAttribute('data-active-step','1');await page.keyboard.press('End');await expect(tour).toHaveAttribute('data-active-step','2');
 await tour.locator('[data-rf-playback]').focus();await page.keyboard.press('Enter');await page.mouse.move(1,990);await expect(tour).toHaveClass(/is-playing/);await page.clock.runFor(8600);await expect(tour).toHaveAttribute('data-active-step','0');await page.locator('#planning').scrollIntoViewIfNeeded();await expect(tour).not.toHaveClass(/is-playing/);await page.clock.runFor(8600);await expect(tour).toHaveAttribute('data-active-step','0');await page.emulateMedia({reducedMotion:'reduce'});await expect(tour.locator('[data-rf-playback]')).toBeDisabled();expect(await page.locator('.rf-stage-backdrop').evaluate(e=>getComputedStyle(e,'::after').animationName)).toBe('none');
});
test('no-JS content and saved Indonesian preference',async({browser})=>{
 const noJS=await browser.newContext({javaScriptEnabled:false}),page=await noJS.newPage();await page.goto('http://127.0.0.1:8765/use-cases/retail-franchises');await expect(page.locator('h1')).toBeVisible();await expect(page.locator('.rf-tour-panel').first()).toBeVisible();await expect(page.locator('.rf-walk-card')).toHaveCount(4);await expect(page.locator('[data-rf-tabs]')).toBeHidden();await noJS.close();
 const ctx=await browser.newContext();await ctx.addInitScript(()=>localStorage.setItem('fluxyos-lang','id'));const p=await ctx.newPage();await p.goto('http://127.0.0.1:8765/use-cases/retail-franchises');await expect(p).toHaveURL(/\/id\/use-cases\/retail-franchises$/);await ctx.close();
});
test('asset resolution, transparency and shared navbar mapping',async({page})=>{
 const manifest=require('../assets/images/navbar-3d/manifest.json');for(const prefix of['','/id']){await page.goto(prefix+'/use-cases/retail-franchises');await expect(page.locator('nav[data-animate=nav]')).toHaveAttribute('data-public-nav-ready','true');await expect(page.locator('nav[data-animate=nav] [data-nav-entry]')).toHaveCount(36);await expect(page.locator('[aria-controls="agency-nav-panel-2"]')).toBeVisible();await page.locator('[aria-controls="agency-nav-panel-2"]').focus();await page.keyboard.press('ArrowDown');await expect(page.locator(`#agency-nav-panel-2 a[href="${prefix?'/use-cases/retail-franchises':'/id/use-cases/retail-franchises'}"]`)).toBeVisible();await page.keyboard.press('Escape');for(const[id,m]of Object.entries(manifest))await expect(page.locator(`nav[data-animate=nav] [data-nav-entry="${id}"] img`).first()).toHaveAttribute('src','/assets/images/navbar-3d/'+m.asset);}
 for(const filename of ['storefront','stock-parcel','ledger','calculator'])expect(fs.statSync(`assets/images/retail-finance/${filename}.webp`).size).toBeLessThan(50000);
});

test('pointer pause and resume preserves the playback target',async({page})=>{
 await page.goto('/use-cases/retail-franchises');const control=page.locator('[data-rf-playback]');await control.click();await expect(control).toHaveAttribute('aria-pressed','true');await control.click();await expect(control).toHaveAttribute('aria-pressed','false');await page.mouse.move(1,990);await expect(page.locator('[data-retail-tour]')).toHaveClass(/is-playing/);
});
